/**
 * Rendering helpers: turn a Findings report + RemediationResult into console
 * lines and a Markdown PR body. Pure string building — no I/O, no styling
 * dependency (the orchestrator applies colors).
 */

const PR_TITLE = "security: remove PolinRider malware artifacts";

/** Plain lines describing what the scanner found (for console output). */
export function findingLines(findings) {
  return findings.findings.map((f) => {
    const tag = f.contentConfirmed ? "[confirmed]" : "[review]";
    return `${tag} ${f.file}: ${f.description}`;
  });
}

/** Plain lines describing what remediation did (or would do). */
export function resultLines(result) {
  const verb = result.dryRun ? "would " : "";
  const lines = [];
  for (const f of result.applied) {
    lines.push(`${verb}fixed ${f.file}: ${f.description ?? f.action}`);
  }
  for (const n of result.notes) lines.push(n);
  for (const s of result.skipped) {
    lines.push(`skipped ${s.finding.file}: ${s.reason}`);
  }
  return lines;
}

/**
 * Build a Markdown PR body that lists exactly what changed, plus a manual-review
 * section. Replaces the old static PR_BODY so reviewers see a precise diff.
 */
export function buildPrBody({ findings, result }) {
  const out = [];
  out.push("## PolinRider malware cleanup");
  out.push("");
  out.push(
    "Automatically generated by polinrider-remover. Every change below was confirmed by a known PolinRider signature. The scanner reads files as inert text and never executes them.",
  );
  out.push("");

  const REMOVAL_ACTIONS = new Set(["remove-dir", "remove-font-set", "delete-font", "remove-artifact"]);
  const fixed = [];
  for (const f of result.applied) {
    const what = REMOVAL_ACTIONS.has(f.action) || result.filesDeleted.includes(f.file) ? "removed" : "cleaned";
    fixed.push(`- \`${f.file}\`: ${what} — ${f.description ?? f.action}`);
  }
  for (const n of result.notes) fixed.push(`- ${n}`);

  if (fixed.length) {
    out.push("### Removed / fixed");
    out.push(...fixed);
    out.push("");
  }

  const review = [
    ...findings.manualReview.map((m) => `- ${m}`),
    ...result.skipped.map((s) => `- \`${s.finding.file}\`: ${s.reason}`),
  ];
  if (review.length) {
    out.push("### Needs manual review");
    out.push(...review);
    out.push("");
  }

  out.push(
    "> ⚠️ Also check the affected developer's machine for the initial dropper (a malicious npm global package or VS Code extension), and rotate any secrets that may have been exposed via committed `.env` files.",
  );
  out.push("");
  return out.join("\n");
}

export { PR_TITLE };

// ─── Whole-run report (persisted to the reports volume) ─────────────────────────
//
// A `run` object is assembled by the orchestrator:
//   { scannedAt, scannedAtHuman, account:{kind,owner}, dryRun, autoMerge, mergeMethod,
//     totals:{total,clean,infected,remediated,merged,prOpened,manualOnly,errors},
//     repos:[ { repo, severity, findings:[{file,action,confidence,contentConfirmed,description}],
//               deleted:[], modified:[], notes:[], manualReview:[],
//               pr:{url,merged,mergeError}|null, error:string|null } ] }

/** Machine-readable run report. */
export function buildRunJson(run) {
  return { schema: "polinrider-run/1", ...run };
}

function repoChangeSummary(r) {
  const parts = [];
  if (r.deleted?.length) parts.push(`removed: ${r.deleted.join(", ")}`);
  if (r.modified?.length) parts.push(`cleaned: ${r.modified.join(", ")}`);
  for (const n of r.notes ?? []) parts.push(n);
  return parts.join(" · ") || "—";
}

/** Human-readable Markdown run report (clickable PR links + per-repo trace). */
export function buildRunMarkdown(run) {
  const t = run.totals;
  const out = [];
  out.push("# PolinRider Malware Scan — Remediation Report");
  out.push("");
  out.push(`**Last scanned:** ${run.scannedAtHuman ?? run.scannedAt}`);
  out.push(`**Account:** ${run.account.kind} \`${run.account.owner}\``);
  const modes = [];
  if (run.dryRun) modes.push("DRY RUN — no changes written");
  modes.push(run.autoMerge ? `auto-merge: on (${run.mergeMethod})` : "auto-merge: off");
  out.push(`**Mode:** ${modes.join(" · ")}`);
  out.push("");

  out.push("## Summary");
  out.push("");
  out.push("| Metric | Count |");
  out.push("| --- | ---: |");
  out.push(`| Repos scanned | ${t.total} |`);
  out.push(`| Clean | ${t.clean} |`);
  out.push(`| Infected | ${t.infected} |`);
  out.push(`| Remediated | ${t.remediated} |`);
  out.push(`| PRs opened | ${t.prOpened} |`);
  if (run.autoMerge) out.push(`| PRs merged | ${t.merged} |`);
  out.push(`| Needs manual review | ${t.manualOnly} |`);
  out.push(`| Errors | ${t.errors} |`);
  out.push("");

  const withPr = run.repos.filter((r) => r.pr && r.pr.url);
  if (withPr.length) {
    out.push(`## Pull requests (${withPr.length})`);
    out.push("");
    out.push("Review and merge the PR for the project(s) you work on.");
    out.push("");
    out.push("| Repository | Pull request | Status | Changes |");
    out.push("| --- | --- | --- | --- |");
    for (const r of withPr) {
      const name = r.repo.split("/")[1] ?? r.repo;
      const num = r.pr.url.split("/pull/")[1] ?? "PR";
      const status = r.pr.merged ? "✅ merged" : r.pr.mergeError ? "⚠️ merge blocked" : "open";
      out.push(
        `| [${name}](https://github.com/${r.repo}) | [#${num}](${r.pr.url}) | ${status} | ${repoChangeSummary(r)} |`,
      );
    }
    out.push("");
  }

  const attention = run.repos.filter(
    (r) =>
      r.error ||
      (r.pr && r.pr.mergeError) ||
      (r.manualReview && r.manualReview.length) ||
      (r.severity === "infected" && !(r.pr && r.pr.url) && !run.dryRun),
  );
  if (attention.length) {
    out.push("## Needs attention");
    out.push("");
    for (const r of attention) {
      const bits = [];
      if (r.error) bits.push(`error: ${r.error}`);
      if (r.pr && r.pr.mergeError) bits.push(`auto-merge blocked: ${r.pr.mergeError}`);
      if (r.manualReview?.length) bits.push(`manual review: ${r.manualReview.join("; ")}`);
      if (r.severity === "infected" && !(r.pr && r.pr.url) && !run.dryRun && !r.error)
        bits.push("infected but no automated fix applied");
      out.push(`- **${r.repo}** — ${bits.join(" · ").replace(/\s+/g, " ").trim()}`);
    }
    out.push("");
  }

  out.push("---");
  out.push(`_Generated by polinrider-remover at ${run.scannedAt}._`);
  out.push("");
  return out.join("\n");
}
